# Due to how Astro handles type inference with this structure,
# we need to prefix all configuration keys with an underscore.

[_.site]
baseUrl = "http://cyhriside.quest"

[_.globalMeta]
title = "This is Me. "
description = "Retro-Inspired Theme & Built for Astro"
longDescription = "AI Engineer. Solutions Engineering. Economist. Social Scientist."
cardImage = "http://cyhriside.quest/aisingapore.webp"
keywords = ["web development", "design", "technology"]

[_.resumeMeta]
title = "Christopher's Resume"
description = "Practical wisdom, unfiltered thoughts, and hot takes."
longDescription = "Web development, tech trends, and the occasional programming mishap."
cardImage = "http://cyhriside.quest/aisingapore.webp"
keywords = ["web development", "design", "technology"]

[_.blogMeta]
title = "Christopher's Blog"
description = "Practical wisdom, unfiltered thoughts, and hot takes."
longDescription = "Web development, tech trends, and the occasional programming mishap."
cardImage = "http://cyhriside.quest/aisingapore.webp"
keywords = ["web development", "design", "technology"]

[_.projectMeta]
title = "Christopher's Projects"
description = "A list of my web development projects and developer tools."
longDescription = "All of my projects, including both frontend and full-stack applications."
cardImage = "http://cyhriside.quest/aisingapore.webp"
keywords = ["web development", "design", "technology"]

[_.notFoundMeta]
title = "Zaggonaut 404"
description = "The page you are looking for does not exist."
longDescription = "The page you are looking for does not exist. Maybe it never existed. Spooky."
cardImage = "http://cyhriside.quest/aisingapore.webp"

[_.hero]
title = "Hello! I'm Christopher."
subtitle = "AI Enthusiast, Solutions Engineering, Economist."
image = "http://cyhriside.quest/aisingapore.webp"
ctaText = "View Projects"
ctaUrl = "/projects"

[_.personal]
name = "Christopher Hoo"
githubProfile = "https://github.com/cyh002"
# twitterProfile = "https://twitter.com"
linkedinProfile = "https://www.linkedin.com/in/christopher-chi-yang-hoo-570698bb/"

[_.texts]
articlesName = "Articles"
projectsName = "Projects"
resumeName = "Resume"
viewAll = "View All"
noArticles = "No articles found."
noProjects = "No projects found."
noResume = "No resume found."

[_.menu]
home = "/"
projects = "/projects"
blog = "/blog"
resume = "/resume"